services:
  postgres:
    image: postgres:15
    container_name: postgres_db

    environment:
      POSTGRES_DB: library
      POSTGRES_USER: library
      POSTGRES_PASSWORD: library

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U library -d library" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: